name: tests-e2e
permissions:
  contents: read
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install --yes libssl-dev postgresql-client iputils-ping ssh
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "${{env.GO_VERSION}}"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: latest
          traefik-enabled: false
      - name: Run
        run: |
          go version
          which go
          whoami
          make build-e2e
          make install-cli
          ./bin/octelium-e2e
